### ISSUE TITLE
Exception during the second login using different accounts

### ISSUE THREAD

**Issue by chaoranxie** [auth0-samples/auth0-django-web-app#10]
Hi auth0 team, 

Try to see if anyone can help me out, I got this code to work with my account, which allows social login like facebook as well as Google. I tried to log in using both, but got the following error 

```
File "/Users/chaoranxie/dev/auth0-django-web-app/01-Login/auth0login/views.py" in dashboard
  15.     auth0user = user.social_auth.get(provider="auth0")

File "/Users/chaoranxie/.virtualenvs/01-Login--MkF-23Z/lib/python3.6/site-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/Users/chaoranxie/.virtualenvs/01-Login--MkF-23Z/lib/python3.6/site-packages/django/db/models/query.py" in get
  407.             (self.model._meta.object_name, num)

Exception Type: MultipleObjectsReturned at /dashboard
Exception Value: get() returned more than one UserSocialAuth -- it returned 2!
```

Been trying to debug this myself but have no luck, my guess is that is has something to do with the first time you log in there is a session/cookies variable set but when you try to login with a second account, the system is getting both user for some reason

**Comment by jimmyjames** [comment]
Closing this issue as it is quite old - if you are still experiencing this issue please reopen or create a new issue, including any updated information if applicable.

**Comment by ShaynaMichaels** [comment]
I just experienced this issue as well
