### ISSUE TITLE
django-allauth and auth0 

### ISSUE THREAD

**Issue by shazadan** [auth0-samples/auth0-django-web-app#17]
I am trying to integrate Auth0 using django-allauth as the only means for setting up users and auth/authorization of these users. I tried to follow the Django Auth0 Login tutorial you wrote using social-auth-app-django but have not been successful with the django-allauth package. 

I am using  the custom user model in https://github.com/pydanny/cookiecutter-django template as my staring point. I was hoping you could help me bridge the gap in my understanding on how to integrate the two.

**Comment by alexisluque** [comment]
Hi @shazadan, to integrate Auth0 with django-allauth follow the steps:
In the root directory of the project created by cookie cutter, go to **config/settings/base.yml** file:
* In `THIRD_PARTY_APPS` add the Auth0 provider
```python
THIRD_PARTY_APPS = [
    # ...
    'allauth.socialaccount.providers.auth0',
]
```
* Add you Auth0's domain:
```python
SOCIALACCOUNT_PROVIDERS = {
    'auth0': {
        'AUTH0_URL': 'https://youraccount.auth0.com',
    }
}
```

For the next step you need the Django admin user created.
Log in into django admin site (http://yoururl/admin). Once logged in, you need to create a social app for your Auth0 app, Go to http://yoururl/admin/socialaccount/socialapp/add/, and fill the form with the following information:
* On provider combobox select Auth0.
* Set the name you want for your app.
* Set up **Client Id** and **Secret Key** with **Client ID** and **Client Secret** respectively from your [Auth0's dashboard](https://manage.auth0.com/#/applications).
* In sites, add the site in *Available sites* into *Choosen sites*.

**Comment by shazadan** [comment]
@alexisluque thanks for the instructions. I will let you know how it goes.

**Comment by shazadan** [comment]
@alexisluque have you had a chance to review the above error?

**Comment by aaguiarz** [comment]
Hi @shazadan, can you provide us a sample we can run and test?

Thanks

**Comment by shazadan** [comment]
@aaguiarz 

I have outlined the steps to replicate the problem:

Step 1. Download and install django cookie cutter by following instructions at https://github.com/pydanny/cookiecutter-django

Step 2.  Follow the '[Getting Up and Running Locally With Docker](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html)'

Step 3.  Follow steps outlined by @alexisluque to integrate auth0 with django using allauth

Step 4. Setup a user account in Auth0

Step 5. Try logging in with that user in django and you will get the above error.

Best,

Shazada

**Comment by alexisluque** [comment]
@shazadan try the following:
Go to application settings in your [dahsborad](https://manage.auth0.com/#/applications), click on *Show Advanced Settings*, in *OAut* tab disable the option *OIDC Conformant*.

**Comment by shazadan** [comment]
I turned if off and am still getting the same error. 
 
![screen shot 2018-06-19 at 9 00 01 pm](https://user-images.githubusercontent.com/5876591/41636528-e6a5f85a-7403-11e8-821b-924bbca2a2f2.png)

**Comment by aaguiarz** [comment]
@shazadan
when OIDC conformant = true, Auth0 returns the following profile https://auth0.com/docs/user-profile/normalized/oidc

when OIDC conformant = false, Auth0 returns the following profile https://auth0.com/docs/user-profile/normalized/auth0#sample-user-profiles

allauth is using this code to read the profile:

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/auth0/provider.py#L26

We are going to submit a PR to allauth so it works with both profile structures, meanwhile, the instructions @alexisluque gave have been working for both of us. Can you paste the error you are getting now?

**Comment by shazadan** [comment]
@aaguiarz Sorry for delayed response but I spent the weekend trying to debug what might be causing the error. Just to make sure I was following the above instructions I recreated the app twice but I keep getting the same KeyError. Would it be possible for you to jump on a screenshare with me this week and see what I am doing wrong.

**Comment by jimmyjames** [comment]
Closing this issue as it is quite old - if you are still experiencing this issue please reopen or create a new issue, including any updated information if applicable.
