### ISSUE TITLE
Error trying to return details['user_id'] on get_user_id 

### ISSUE THREAD

**Issue by mauroka** [auth0-samples/auth0-django-web-app#3]
Hello, I have implemented this app recently.
The problem I am having is in the get_user_id function in auth0backend.py when I try to return details['user_id'].
I have inspected the available options in details and actually there is no user_id. The options are:
{'username', 'picture', 'first_name', 'email'}

I am returning the email instead. You think there is a problema doing that. I am not quite sure when the get_user_id function it called.

Thanks a lot for the help.

**Comment by aaguiarz** [comment]
Thanks for reporting it. It's fixed https://github.com/auth0-samples/auth0-django-web-app/commit/bfc0651a9010fa42c71dae326a5975cdfddfe78d
