### ISSUE TITLE
Django sample builds from scratch, but there is an existing Auth0 backend.

### ISSUE THREAD

**Issue by jleclanche** [auth0-samples/auth0-django-web-app#30]
This sample: https://auth0.com/docs/quickstart/webapp/django/01-login

Builds a new Auth0 backend from scratch, which is probably not what most Django users want given that python-social-auth has an auth0 backend available:

https://github.com/python-social-auth/social-core/blob/master/social_core/backends/auth0.py

**Comment by jleclanche** [comment]
shrug

**Comment by jleclanche** [comment]
.

**Comment by jleclanche** [comment]
stalebots aren't useful

**Comment by jleclanche** [comment]
@lbalmaceda please disable stalebot on issues where it's gotten replied off -- or better yet, disable stalebot altogether: https://drewdevault.com/2021/10/26/stalebot.html

**Comment by evansims** [comment]
Hi @jleclanche 👋 Your feedback is appreciated! We'll keep your suggestion in mind for future changes to the quickstart. As this isn't something immediately actionable for us, we'll close this issue for now.

**Comment by jleclanche** [comment]
@evansims its very actionable, it’s documentation feedback and you could replace the doc with a recommendation to use that library

**Comment by evansims** [comment]
Hey @jleclanche 👋 I understand, but it isn't immediately actionable for us as we do not have any major changes for this quickstart planned for the near term. We do appreciate the feedback and will consider it for future updates.
