### ISSUE TITLE
Feature request: integrate auth0 login with app-generator/django-user-profile

### ISSUE THREAD

**Issue by aculich** [auth0-samples/auth0-django-web-app#31]
I opened a [feature request](https://github.com/app-generator/django-user-profile/issues/4) with [app-generator/django-user-profile](https://github.com/app-generator/django-user-profile) to integrate auth0 as part of their example.

This repo that you provide is very helpful as a very minimalistic auth0 app to get something going, but I've found it difficult to integrate your example with this other useful user profile example.

It would be even better if you could provide some examples of using user_metadata as well.

Thanks!

**Comment by evansims** [comment]
Hi @aculich 👋 Appreciate your feedback! We'll keep your suggestion in mind for future improvements to the quickstart. In the meantime be sure to reach out to the [Auth0 Community](https://community.auth0.com/tag/python) for additional guidance on usage. (As this isn't something immediately actionable for us, we'll close this issue for now, but thanks again!)
