### ISSUE TITLE
The specified alg value is not allowed

### ISSUE THREAD

**Issue by mauroka** [auth0-samples/auth0-django-web-app#6]
Hello, I am having a problem when trying to authenticate following this example.
The error occurs in this line:
payload = jwt.decode(idToken, jwks.read(), algorithms=['RS256'], audience=audience, issuer=issuer)

Actually, the jwt.py packages raises an JWTError(e): The specified alg value is not allowed

According to this issue https://github.com/jpadilla/pyjwt/issues/236 it happens because: The JWT token does not have it's alg header set to "RS256" which probably means it was encoded using the wrong algorithm.

I am using the Auth0 version 2 API, specific version 6975. You think maybe adding some algorithms in the algorithms list will help? Like:
algorithms=['RS256', 'RSA', 'HMAC']

Thanks a lot for the help.
Cheers.

**Comment by aaguiarz** [comment]
You need to set your client to use RS256:

![image](https://user-images.githubusercontent.com/1636576/31789082-46619664-b4e7-11e7-92e1-6623b7e10d05.png)

**Comment by mauroka** [comment]
Hi @aaguiarz, thanks a lot for the reply.
In case I would like to support both RS256 and HS256, how can I accomplished that?
I've tried algorithms=['RS256', 'HS256'] but it throws an error:
Incorrect key type.  Expected: 'oct', Recieved: RSA
jwk.py in _process_jwk, line 122

Thanks a lot.

**Comment by aaguiarz** [comment]
You can't do that with that library, you need to specify the algorithm the token has been signed with.

You should always use RS256 as HS256 can be brute-forced https://auth0.com/blog/brute-forcing-hs256-is-possible-the-importance-of-using-strong-keys-to-sign-jwts/

**Comment by mauroka** [comment]
Ok @aaguiarz. 
Thanks a lot. You've really helpful.

**Comment by mauroka** [comment]
Hi @aaguiarz.
When I have to use HS256 I use PyJWT like this:
payload = jwt.decode(idToken, self.setting('SOCIAL_AUTH_AUTH0_SECRET'), algorithms=['HS256'], audience=audience, issuer=issuer)

I know it can be brute-forced but maybe someone wants to set this in Auth0 Client.
Thanks a lot for your help.
